### ISSUE TITLE
Add more info on minefields, APCs, etc when intel found

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi-1.4#13]
"Intel Found" about mines or any other things doesn't help in anyway, the mine field area should be marked on the map at least, and that marker should stay even after restarts, and for vehicles it is not really easy to get, when said they got APCs or Helicopters it would help to know where for example or what

**Comment by wurzel0701** [comment]
The mines are a good point, instead of just revealing them, there should be a persistent marker on the map.

The where is nearly impossible to say for vehicles as they are spawned in whereever needed, there is no way to properly know this. It would be possible to get the type of available vehicles and the time when they can be used again as intel

**Comment by Toakan** [comment]
#139 Is being used to fix this.

**Comment by wurzel0701** [comment]
Code done, needs testing and someone to have a look on it

**Comment by Spoffy** [comment]
Replaced by #139
